### ISSUE TITLE
Current Todo

### ISSUE THREAD

**Issue by ROODAY** [philsiff/ChatAnon#7]
- [x] Fix links put in chat. The ripple layer is overlaid so the links can't be clicked on. Try making the links' z-index higher. Also, make sure links open in new tab. <-- To do this, the ripple layer had to be removed. Acceptable losses for now.
- [ ] The new message indicator that changes the name of the tab dynamically, similar to facebook chat, is not working. Use [this](http://webdesign.tutsplus.com/tutorials/how-to-display-update-notifications-in-the-browser-tab--cms-23458)
- [x] User count does not update when people leave
- [ ] Sometimes the messages randomly clears
- [ ] Make a new logo, something creative, more involving the chat aspect
- [ ] Improve the UI so that it scales well for mobile, possible make a mobile client app
- [ ] Add an embed button that lets people paste in video/audio that will enter the chat that people can watch, listen to
- [x] Add an info button at top left to say who made it, and provide an email for suggestions/comments <-- Should we ask for donations for server upkeep?

Please add to this list as you see fit
@liboan, @philsiff

**Comment by ROODAY** [comment]
Anyone have any ideas for future features?

**Comment by ROODAY** [comment]
Didn't realize this was still open, closing out so I can archive this
